### ISSUE TITLE
Store data inside flash

### ISSUE THREAD

**Issue by dzonerzy** [im-tomu/tomu-hardware#33]
As it states there's a way to store data inside tomu?

**Comment by xobs** [comment]
To the best of my knowledge, there aren't any examples of this yet.  You need to be very, very careful, because you can very easily erase Toboot, meaning your board won't boot anymore.

An example of something that stores data on the flash is Booster (https://github.com/im-tomu/tomu-bootloader/blob/master/booster/main.c#L127), which is used to update Toboot.

Tomu has 1024-byte pages.  Since there are 64 kB on the device, that means there are 64 pages in total.  Toboot takes up the first 8 pages.

To program data, you must:

1. Erase a 1024-byte block
2. Program your data in 4-byte words.

That's what that loop does: It erases an 1024-byte block, then loops through the data to write and programs it 4-bytes at a time.

You _must_ erase a block before programming data, otherwise you can damage the flash.

As long as you make sure to never pass a `target_addr` that's <= 8192, the `ftfl_begin_erase_sector()` and `ftfl_begin_program_word()` functions can be used in your program.  To make life easier, you could make sure `target_addr` is always something towards the end of flash, like address 61440 (= 60*1024).
